const ERROR_CODES = {
  0: "OK",
  1: "InternalError",
  2: "BadValue",
  3: "OBSOLETE_DuplicateKey",
  4: "NoSuchKey",
  5: "GraphContainsCycle",
  6: "HostUnreachable:categories: [NetworkError:RetriableError]",
  7: "HostNotFound:categories: [NetworkError:RetriableError]",
  8: "UnknownError",
  9: "FailedToParse",
  10: "CannotMutateObject",
  11: "UserNotFound",
  12: "UnsupportedFormat",
  13: "Unauthorized",
  14: "TypeMismatch",
  15: "Overflow:categories: [ValidationError]",
  16: "InvalidLength",
  17: "ProtocolError",
  18: "AuthenticationFailed",
  19: "CannotReuseObject",
  20: "IllegalOperation",
  21: "EmptyArrayOperation",
  22: "InvalidBSON:categories: [ValidationError]",
  23: "AlreadyInitialized",
  24: "LockTimeout:categories: [Interruption]",
  25: "RemoteValidationError",
  26: "NamespaceNotFound",
  27: "IndexNotFound",
  28: "PathNotViable",
  29: "NonExistentPath",
  30: "InvalidPath",
  31: "RoleNotFound",
  32: "RolesNotRelated",
  33: "PrivilegeNotFound",
  34: "CannotBackfillArray",
  35: "UserModificationFailed",
  36: "RemoteChangeDetected",
  37: "FileRenameFailed",
  38: "FileNotOpen",
  39: "FileStreamFailed",
  40: "ConflictingUpdateOperators",
  41: "FileAlreadyOpen",
  42: "LogWriteFailed",
  43: "CursorNotFound:categories: [CursorInvalidatedError]",
  45: "UserDataInconsistent",
  46: "LockBusy",
  47: "NoMatchingDocument",
  48: "NamespaceExists",
  49: "InvalidRoleModification",
  50: "MaxTimeMSExpired:categories: [Interruption:ExceededTimeLimitError]",
  51: "ManualInterventionRequired",
  52: "DollarPrefixedFieldName",
  53: "InvalidIdField",
  54: "NotSingleValueField",
  55: "InvalidDBRef",
  56: "EmptyFieldName",
  57: "DottedFieldName",
  58: "RoleModificationFailed",
  59: "CommandNotFound",
  60: "OBSOLETE_DatabaseNotFound",
  61: "ShardKeyNotFound",
  62: "OplogOperationUnsupported",
  63: "OBSOLETE_StaleShardVersion",
  64: "WriteConcernFailed:categories: [WriteConcernError]",
  65: "MultipleErrorsOccurred: extra: MultipleErrorsOccurredInfo",
  66: "ImmutableField",
  67: "CannotCreateIndex",
  68: "IndexAlreadyExists",
  69: "AuthSchemaIncompatible",
  70: "ShardNotFound",
  71: "ReplicaSetNotFound",
  72: "InvalidOptions",
  73: "InvalidNamespace",
  74: "NodeNotFound",
  75: "WriteConcernLegacyOK:categories: [WriteConcernError]",
  76: "NoReplicationEnabled",
  77: "OperationIncomplete",
  78: "CommandResultSchemaViolation",
  79: "UnknownReplWriteConcern:categories: [WriteConcernError]",
  80: "RoleDataInconsistent",
  81: "NoMatchParseContext",
  82: "NoProgressMade",
  83: "RemoteResultsUnavailable",
  84: "OBSOLETE_DuplicateKeyValue",
  85: "IndexOptionsConflict",
  86: "IndexKeySpecsConflict",
  87: "CannotSplit",
  88: "OBSOLETE_SplitFailed",
  89: "NetworkTimeout:categories: [NetworkError:RetriableError:NetworkTimeoutError]",
  90: "CallbackCanceled:categories: [CancellationError]",
  91: "ShutdownInProgress: extra: ShutdownInProgressQuiesceInfo: categories: [ShutdownError:CancellationError:RetriableError]:                       extraIsOptional: True",
  92: "SecondaryAheadOfPrimary",
  93: "InvalidReplicaSetConfig",
  94: "NotYetInitialized",
  95: "NotSecondary",
  96: "OperationFailed:categories: [CursorInvalidatedError]",
  97: "NoProjectionFound",
  98: "DBPathInUse",
  100: "UnsatisfiableWriteConcern:categories: [WriteConcernError]",
  101: "OutdatedClient",
  102: "IncompatibleAuditMetadata",
  103: "NewReplicaSetConfigurationIncompatible",
  104: "NodeNotElectable",
  105: "IncompatibleShardingMetadata",
  106: "DistributedClockSkewed",
  107: "LockFailed",
  108: "InconsistentReplicaSetNames",
  109: "ConfigurationInProgress",
  110: "CannotInitializeNodeWithData",
  111: "NotExactValueField",
  112: "WriteConflict",
  113: "InitialSyncFailure",
  114: "InitialSyncOplogSourceMissing",
  115: "CommandNotSupported",
  116: "DocTooLargeForCapped",
  117: "ConflictingOperationInProgress",
  118: "NamespaceNotSharded",
  119: "InvalidSyncSource",
  120: "OplogStartMissing",
  121: "DocumentValidationFailure: extra: 'doc_validation_error::DocumentValidationFailureInfo'",
  122: "OBSOLETE_ReadAfterOptimeTimeout",
  123: "NotAReplicaSet",
  124: "IncompatibleElectionProtocol",
  125: "CommandFailed",
  126: "RPCProtocolNegotiationFailed",
  127: "UnrecoverableRollbackError",
  128: "LockNotFound",
  129: "LockStateChangeFailed",
  130: "SymbolNotFound",
  132: "OBSOLETE_ConfigServersInconsistent",
  133: "FailedToSatisfyReadPreference",
  134: "ReadConcernMajorityNotAvailableYet: categories: [RetriableError]",
  135: "StaleTerm",
  136: "CappedPositionLost",
  137: "IncompatibleShardingConfigVersion",
  138: "RemoteOplogStale",
  139: "JSInterpreterFailure",
  140: "InvalidSSLConfiguration",
  141: "SSLHandshakeFailed",
  142: "JSUncatchableError",
  143: "CursorInUse",
  144: "IncompatibleCatalogManager",
  145: "PooledConnectionsDropped",
  146: "ExceededMemoryLimit",
  147: "ZLibError",
  148: "ReadConcernMajorityNotEnabled:categories: [VoteAbortError]",
  149: "NoConfigPrimary",
  150: "StaleEpoch: categories: [StaleShardVersionError:NeedRetargettingError]: extra: StaleEpochInfo: extraIsOptional: True",
  151: "OperationCannotBeBatched",
  152: "OplogOutOfOrder",
  153: "ChunkTooBig",
  154: "InconsistentShardIdentity",
  155: "CannotApplyOplogWhilePrimary",
  156: "OBSOLETE_NeedsDocumentMove",
  157: "CanRepairToDowngrade",
  158: "MustUpgrade",
  159: "DurationOverflow",
  160: "MaxStalenessOutOfRange",
  161: "IncompatibleCollationVersion",
  162: "CollectionIsEmpty",
  163: "ZoneStillInUse",
  164: "InitialSyncActive",
  165: "ViewDepthLimitExceeded",
  166: "CommandNotSupportedOnView",
  167: "OptionNotSupportedOnView",
  168: "InvalidPipelineOperator",
  169: "CommandOnShardedViewNotSupportedOnMongod:extra: ResolvedView",
  170: "TooManyMatchingDocuments",
  171: "CannotIndexParallelArrays",
  172: "TransportSessionClosed",
  173: "TransportSessionNotFound",
  174: "TransportSessionUnknown",
  175: "QueryPlanKilled:categories: [CursorInvalidatedError]",
  176: "FileOpenFailed",
  177: "ZoneNotFound",
  178: "RangeOverlapConflict",
  179: "WindowsPdhError",
  180: "BadPerfCounterPath",
  181: "AmbiguousIndexKeyPattern",
  182: "InvalidViewDefinition",
  183: "ClientMetadataMissingField",
  184: "ClientMetadataAppNameTooLarge",
  185: "ClientMetadataDocumentTooLarge",
  186: "ClientMetadataCannotBeMutated",
  187: "LinearizableReadConcernError",
  188: "IncompatibleServerVersion",
  189: "PrimarySteppedDown:categories: [NotPrimaryError:RetriableError]",
  190: "MasterSlaveConnectionFailure",
  191: "OBSOLETE_BalancerLostDistributedLock",
  192: "FailPointEnabled",
  193: "NoShardingEnabled",
  194: "BalancerInterrupted",
  195: "ViewPipelineMaxSizeExceeded",
  197: "InvalidIndexSpecificationOption",
  198: "OBSOLETE_ReceivedOpReplyMessage",
  199: "ReplicaSetMonitorRemoved",
  200: "ChunkRangeCleanupPending",
  201: "CannotBuildIndexKeys",
  202: "NetworkInterfaceExceededTimeLimit:categories: [ExceededTimeLimitError:NetworkTimeoutError]",
  203: "ShardingStateNotInitialized",
  204: "TimeProofMismatch",
  205: "ClusterTimeFailsRateLimiter",
  206: "NoSuchSession",
  207: "InvalidUUID",
  208: "TooManyLocks",
  209: "StaleClusterTime",
  210: "CannotVerifyAndSignLogicalTime",
  211: "KeyNotFound",
  212: "IncompatibleRollbackAlgorithm",
  213: "DuplicateSession",
  214: "AuthenticationRestrictionUnmet",
  215: "DatabaseDropPending",
  216: "ElectionInProgress",
  217: "IncompleteTransactionHistory",
  218: "UpdateOperationFailed",
  219: "FTDCPathNotSet",
  220: "FTDCPathAlreadySet",
  221: "IndexModified",
  222: "CloseChangeStream",
  223: "IllegalOpMsgFlag:categories: [ConnectionFatalMessageParseError]",
  224: "QueryFeatureNotAllowed",
  225: "TransactionTooOld:categories: [VoteAbortError]",
  226: "AtomicityFailure",
  227: "CannotImplicitlyCreateCollection: extra: CannotImplicitlyCreateCollectionInfo",
  228: "SessionTransferIncomplete",
  229: "MustDowngrade",
  230: "DNSHostNotFound",
  231: "DNSProtocolError",
  232: "MaxSubPipelineDepthExceeded",
  233: "TooManyDocumentSequences:categories: [ConnectionFatalMessageParseError]",
  234: "RetryChangeStream",
  235: "InternalErrorNotSupported",
  236: "ForTestingErrorExtraInfo:extra: ErrorExtraInfoExample",
  237: "CursorKilled:categories: [Interruption:CursorInvalidatedError]",
  238: "NotImplemented",
  239: "SnapshotTooOld:categories: [SnapshotError]",
  240: "DNSRecordTypeMismatch",
  241: "ConversionFailure",
  242: "CannotCreateCollection",
  243: "IncompatibleWithUpgradedServer",
  244: "NOT_YET_AVAILABLE_TransactionAborted",
  245: "BrokenPromise",
  246: "SnapshotUnavailable:categories: [SnapshotError]",
  247: "ProducerConsumerQueueBatchTooLarge",
  248: "ProducerConsumerQueueEndClosed",
  249: "StaleDbVersion:extra: StaleDbRoutingVersion",
  250: "StaleChunkHistory:categories: [SnapshotError]",
  251: "NoSuchTransaction:categories: [VoteAbortError]",
  252: "ReentrancyNotAllowed",
  253: "FreeMonHttpInFlight",
  254: "FreeMonHttpTemporaryFailure",
  255: "FreeMonHttpPermanentFailure",
  256: "TransactionCommitted",
  257: "TransactionTooLarge",
  258: "UnknownFeatureCompatibilityVersion",
  259: "KeyedExecutorRetry",
  260: "InvalidResumeToken",
  261: "TooManyLogicalSessions",
  262: "ExceededTimeLimit:categories: [Interruption:ExceededTimeLimitError:RetriableError]",
  263: "OperationNotSupportedInTransaction:categories: [VoteAbortError]",
  264: "TooManyFilesOpen",
  265: "OrphanedRangeCleanUpFailed",
  266: "FailPointSetFailed",
  267: "PreparedTransactionInProgress",
  268: "CannotBackup",
  269: "DataModifiedByRepair",
  270: "RepairedReplicaSetNode",
  271: "JSInterpreterFailureWithStack:extra: JSExceptionInfo",
  272: "MigrationConflict:categories: [SnapshotError]",
  273: "ProducerConsumerQueueProducerQueueDepthExceeded",
  274: "ProducerConsumerQueueConsumed",
  275: "ExchangePassthrough",
  276: "IndexBuildAborted",
  277: "AlarmAlreadyFulfilled",
  278: "UnsatisfiableCommitQuorum",
  279: "ClientDisconnect:categories: [Interruption]",
  280: "ChangeStreamFatalError:categories: [NonResumableChangeStreamError]",
  281: "TransactionCoordinatorSteppingDown:categories: [Interruption]",
  282: "TransactionCoordinatorReachedAbortDecision:categories: [Interruption]",
  283: "WouldChangeOwningShard:extra: WouldChangeOwningShardInfo",
  284: "ForTestingErrorExtraInfoWithExtraInfoInNamespace:                  extra: 'nested::twice::NestedErrorExtraInfoExample'",
  285: "IndexBuildAlreadyInProgress",
  286: "ChangeStreamHistoryLost:categories: [NonResumableChangeStreamError]",
  287: "TransactionCoordinatorDeadlineTaskCanceled:categories: [InternalOnly]",
  288: "ChecksumMismatch:categories: [ConnectionFatalMessageParseError]",
  289: "WaitForMajorityServiceEarlierOpTimeAvailable:categories: [InternalOnly]",
  290: "TransactionExceededLifetimeLimitSeconds: categories: [Interruption:ExceededTimeLimitError]",
  291: "NoQueryExecutionPlans",
  292: "QueryExceededMemoryLimitNoDiskUseAllowed",
  293: "InvalidSeedList",
  294: "InvalidTopologyType",
  295: "InvalidHeartBeatFrequency",
  296: "TopologySetNameRequired",
  297: "HierarchicalAcquisitionLevelViolation",
  298: "InvalidServerType",
  299: "OCSPCertificateStatusRevoked",
  300: "RangeDeletionAbandonedBecauseCollectionWithUUIDDoesNotExist",
  301: "DataCorruptionDetected",
  302: "OCSPCertificateStatusUnknown",
  303: "SplitHorizonChange:categories: [CloseConnectionError]",
  304: "ShardInvalidatedForTargeting:extra: ShardInvalidatedForTargetingInfo",
  306: "ReadThroughCacheLookupCanceled:categories: [InternalOnly]",
  307: "RangeDeletionAbandonedBecauseTaskDocumentDoesNotExist",
  308: "CurrentConfigNotCommittedYet",
  309: "ExhaustCommandFinished",
  310: "PeriodicJobIsStopped:categories: [CancellationError]",
  311: "TransactionCoordinatorCanceled:categories: [InternalOnly]",
  312: "OperationIsKilledAndDelisted:categories: [CancellationError:InternalOnly]",
  313: "ResumableRangeDeleterDisabled",
  314: "ObjectIsBusy: categories: [CursorInvalidatedError]",
  315: "TooStaleToSyncFromSource:categories: [InternalOnly]",
  316: "QueryTrialRunCompleted:categories: [InternalOnly]",
  317: "ConnectionPoolExpired:categories: [NetworkError:RetriableError:InternalOnly]",
  318: "ForTestingOptionalErrorExtraInfo:extra: OptionalErrorExtraInfoExample:extraIsOptional: True",
  319: "MovePrimaryInProgress",
  320: "TenantMigrationConflict:extra: TenantMigrationConflictInfo:categories: [TenantMigrationError: TenantMigrationConflictError]",
  321: "TenantMigrationCommitted: categories: [TenantMigrationError]",
  322: "APIVersionError: categories: [VersionedAPIError]",
  323: "APIStrictError: categories: [VersionedAPIError]",
  324: "APIDeprecationError: categories: [VersionedAPIError]",
  325: "TenantMigrationAborted:categories: [TenantMigrationError]",
  326: "OplogQueryMinTsMissing",
  327: "NoSuchTenantMigration",
  328: "TenantMigrationAccessBlockerShuttingDown: categories: [InternalOnly]",
  329: "TenantMigrationInProgress",
  330: "SkipCommandExecution",
  331: "FailedToRunWithReplyBuilder",
  332: "CannotDowngrade",
  333: "ServiceExecutorInShutdown: categories: [ShutdownError:CancellationError:InternalOnly]",
  334: "MechanismUnavailable",
  335: "TenantMigrationForgotten",
  336: "TimeseriesBucketCleared: categories: [InternalOnly]",
  337: "AuthenticationAbandoned: categories: [InternalOnly]",
  338: "ReshardCollectionInProgress",
  339: "NoSuchReshardCollection",
  340: "ReshardCollectionCommitted",
  341: "ReshardCollectionAborted",
  342: "ReshardingCriticalSectionTimeout",
  343: "ShardCannotRefreshDueToLocksHeld: extra: ShardCannotRefreshDueToLocksHeldInfo",
  344: "AuditingNotEnabled",
  345: "RuntimeAuditConfigurationNotEnabled",
  346: "ChangeStreamInvalidated: extra: ChangeStreamInvalidationInfo",
  347: "APIMismatchError: categories: [VersionedAPIError:VoteAbortError]",
  348: "ChangeStreamTopologyChange: extra: ChangeStreamTopologyChangeInfo",
  349: "KeyPatternShorterThanBound",
  350: "ReshardCollectionTruncatedError",
  351: "ChangeStreamStartAfterInvalidate: extra: ChangeStreamStartAfterInvalidateInfo",
  352: "UnsupportedOpQueryCommand",
  353: "NonRetryableTenantMigrationConflict: extra: NonRetryableTenantMigrationConflictInfo: categories: [TenantMigrationError: TenantMigrationConflictError]",
  354: "LoadBalancerSupportMismatch: categories: [CloseConnectionError]",
  355: "InterruptedDueToStorageChange:categories: [Interruption:CancellationError]",
  356: "TxnRetryCounterTooOld: extra: TxnRetryCounterTooOldInfo: categories: [VoteAbortError]",
  357: "InvalidBSONType",
  358: "InternalTransactionNotSupported: categories: [RetriableError]",
  359: "CannotConvertIndexToUnique: extra: CannotConvertIndexToUniqueInfo",
  360: "PlacementVersionRefreshCanceled: categories: [InternalOnly]",
  361: "CollectionUUIDMismatch: extra: CollectionUUIDMismatchInfo",
  362: "FutureAlreadyRetrieved",
  363: "RetryableTransactionInProgress",
  365: "TemporarilyUnavailable",
  366: "WouldChangeOwningShardDeletedNoDocument",
  367: "FLECompactionPlaceholder",
  369: "FLETransactionAbort",
  370: "CannotDropShardKeyIndex",
  371: "UserWritesBlocked",
  372: "CloseConnectionForShutdownCommand: categories: [CloseConnectionError:InternalOnly]",
  373: "InternalTransactionsExhaustiveFindHasMore",
  374: "TransactionAPIMustRetryTransaction: categories: [InternalOnly]",
  375: "TransactionAPIMustRetryCommit: categories: [InternalOnly]",
  376: "ChangeStreamNotEnabled",
  377: "FLEMaxTagLimitExceeded ",
  378: "NonConformantBSON: categories: [ValidationError]",
  379: "DatabaseMetadataRefreshCanceled: categories: [InternalOnly]",
  380: "RequestAlreadyFulfilled",
  381: "ReshardingCoordinatorServiceConflictingOperationInProgress: extra: ReshardingCoordinatorServiceConflictingOperationInProgressInfo: categories: [InternalOnly]",
  382: "RemoteCommandExecutionError: extra: AsyncRPCErrorInfo: categories: [InternalOnly]",
  383: "CollectionIsEmptyLocally",
  384: "ConnectionError: categories: [NetworkError:RetriableError:InternalOnly]",
  385: "ConflictingServerlessOperation",
  386: "DuplicateKeyId",
  387: "EncounteredFLEPayloadWhileRedacting",
  388: "TransactionTooLargeForCache",
  389: "LibmongocryptError",
  390: "InvalidSignature",
  391: "ReauthenticationRequired",
  392: "InvalidJWT",
  393: "InvalidTenantId",
  394: "MovePrimaryRecipientDocNotFound: categories: [InternalOnly]",
  395: "TruncatedSerialization",
  396: "IndexInformationTooLarge",
  397: "MovePrimaryAborted",
  398: "StreamTerminated: categories: [CloseConnectionError]",
  9001: "SocketException:categories: [NetworkError:RetriableError]",
  9996: "OBSOLETE_RecvStaleConfig",
  10003: "CannotGrowDocumentInCappedNamespace",
  10058: "LegacyNotPrimary",
  10107: "NotWritablePrimary:categories: [NotPrimaryError:RetriableError]",
  10334: "BSONObjectTooLarge",
  11000: "DuplicateKey:extra: DuplicateKeyErrorInfo",
  11600: "InterruptedAtShutdown:categories: [Interruption:ShutdownError:CancellationError:RetriableError]",
  11601: "Interrupted:categories: [Interruption]",
  11602: "InterruptedDueToReplStateChange:categories: [Interruption:NotPrimaryError:RetriableError]",
  12586: "BackgroundOperationInProgressForDatabase",
  12587: "BackgroundOperationInProgressForNamespace",
  13104: "OBSOLETE_PrepareConfigsFailed",
  13113: "MergeStageNoMatchingDocument",
  13297: "DatabaseDifferCase",
  13388: "StaleConfig: extra: StaleConfigInfo: categories: [StaleShardVersionError:NeedRetargettingError]",
  13435: "NotPrimaryNoSecondaryOk:categories: [NotPrimaryError:RetriableError]",
  13436: "NotPrimaryOrSecondary:categories: [NotPrimaryError:RetriableError]",
  14031: "OutOfDiskSpace",
  17280: "OBSOLETE_KeyTooLong",
  46841: "ClientMarkedKilled:categories: [Interruption:CancellationError]",
  50768: "NotARetryableWriteCommand",
  50915: "BackupCursorOpenConflictWithCheckpoint: categories: [RetriableError]",
  56846: "ConfigServerUnreachable",
};

module.exports = { ERROR_CODES };
